import { z } from "zod";


export const NOTIFICATION_TYPE = {
    REFERRAL_CREATED: "REFERRAL_CREATED",
    INCIDENT_CREATED: "INCIDENT_CREATED",
    INCIDENT_CLOSED: "INCIDENT_CLOSED",
    INCIDENT_REOPENED: "INCIDENT_REOPENED",
    INCIDENT_NOTE_ADDED: "INCIDENT_NOTE_ADDED",
    STUDENT_RISK_TURNED_RED: "STUDENT_RISK_TURNED_RED",
} as const;

export const NOTIFICATION_TYPE_VALUES = [
    NOTIFICATION_TYPE.REFERRAL_CREATED,
    NOTIFICATION_TYPE.INCIDENT_CREATED,
    NOTIFICATION_TYPE.INCIDENT_CLOSED,
    NOTIFICATION_TYPE.INCIDENT_REOPENED,
    NOTIFICATION_TYPE.INCIDENT_NOTE_ADDED,
    NOTIFICATION_TYPE.STUDENT_RISK_TURNED_RED,
] as const;

export const notificationTypeSchema = z.enum(NOTIFICATION_TYPE_VALUES);

export type NotificationType = z.infer<typeof notificationTypeSchema>;